version: '3.8'

services:
  chatbot-analyzer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MCP_WORKSPACE=/app/workspace
      - MCP_PORT=3001
    volumes:
      - ./workspace:/app/workspace
      - ./data:/app/data
    restart: unless-stopped
    
  # Optional: Add a simple web UI for reports
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./workspace/reports:/usr/share/nginx/html/reports:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - chatbot-analyzer
    restart: unless-stopped

volumes:
  workspace:
  data: