apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-chatbot
  labels:
    app: rasa-chatbot
    component: chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rasa-chatbot
  template:
    metadata:
      labels:
        app: rasa-chatbot
        component: chatbot
    spec:
      containers:
      - name: rasa
        image: rasa-chatbot:latest
        ports:
        - containerPort: 5005
        env:
        - name: RASA_MODEL_PATH
          value: "/app/models"
        - name: RASA_ACTION_ENDPOINT
          value: "http://rasa-actions:5055/webhook"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /status
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: rasa-models-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: rasa-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-chatbot-service
  labels:
    app: rasa-chatbot
spec:
  selector:
    app: rasa-chatbot
  ports:
  - name: http
    port: 5005
    targetPort: 5005
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-actions
  labels:
    app: rasa-actions
    component: actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa-actions
  template:
    metadata:
      labels:
        app: rasa-actions
        component: actions
    spec:
      containers:
      - name: actions
        image: rasa-chatbot:latest
        command: ["rasa", "run", "actions", "--port", "5055"]
        ports:
        - containerPort: 5055
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-actions
  labels:
    app: rasa-actions
spec:
  selector:
    app: rasa-actions
  ports:
  - name: http
    port: 5055
    targetPort: 5055
  type: ClusterIP